[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # These are placeholders. You will need to set the actual values in the Netlify UI.
  NEXT_PUBLIC_SUPABASE_URL = "YOUR_SUPABASE_URL"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY" 